### ISSUE TITLE
Missing info in README: DRIFT_API_KEY

### ISSUE THREAD

**Issue by timburks** [googleapis/sloth#280]
After setting `SLOTH_GITHUB_TOKEN`, running `sloth` produces this:

```
$ sloth
/usr/local/lib/node_modules/@justinbeckwith/sloth/build/src/issue.js:23
    throw new Error('Please access the `Yoshi Drift Key` secret in go/valentine, and set the `DRIFT_API_KEY` env var.');
    ^

Error: Please access the `Yoshi Drift Key` secret in go/valentine, and set the `DRIFT_API_KEY` env var.
    at Object.<anonymous> (/usr/local/lib/node_modules/@justinbeckwith/sloth/build/src/issue.js:23:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@justinbeckwith/sloth/build/src/slo.js:16:17)
    at Module._compile (module.js:652:30)
```

What is this for? If someone wanted to use `sloth` to monitor a different set of repos, could this be omitted?

**Comment by JustinBeckwith** [comment]
When we initially wrote sloth, there was a small enough number of repositories to manage that we could reasonably use the public GitHub API.  As the # of repositories to query grew, we were unable to do a lot of actions without exhausting the default API quota.  

The DRIFT team runs an instance of [maintnerd](https://godoc.org/golang.org/x/build/maintner/maintnerd) that keeps all of the GitHub issues in the `googleapis` org (among others) synchronized using the GitHub events API to local memory, and exposes those via the DRIFT GitHub API we use here.  

As a result - as of right now this thing is very suited to to our specific use case.

**Comment by JustinBeckwith** [comment]
This is moving to a mostly private tool, so closing this out.
