### ISSUE TITLE
Create new team for Cloud Trace

### ISSUE THREAD

**Issue by ZiweiZhao** [googleapis/sloth#652]
**Is your feature request related to a problem? Please describe.**
Cloud-trace team is taking over cloud-trace-nodejs agent, and trying to create a new team for us.

**Comment by ZiweiZhao** [comment]
Also, when running `sloth` command, I'm seeing error of ```/usr/local/lib/node_modules/@justinbeckwith/sloth/build/src/issue.js:24
    throw new Error('Please access the `Yoshi Drift Key` secret in go/valentine, and set the `DRIFT_API_KEY` env var.');
    ^

Error: Please access the `Yoshi Drift Key` secret in go/valentine, and set the `DRIFT_API_KEY` env var.
    at Object.<anonymous> (/usr/local/lib/node_modules/@justinbeckwith/sloth/build/src/issue.js:24:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@justinbeckwith/sloth/build/src/slo.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)```
When I go to valentine, I could not see the secret. Am I lacking permission here? 
Thanks in advance!

**Comment by JustinBeckwith** [comment]
Greetings folks!  We're starting to ramp down team management like this in sloth.  I went ahead and created a GitHub team named `api-trace`, and invited both of y'all from the PR to the team.  The team has write access to `googleapis/cloud-trace-nodejs` :) Let us know if you need anything else!
